baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Arthur Costa'
theme = 'devise'
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2025, Arthur Costa"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90

# Configuration Features
[params]
  description = "Information Technology student at IMD/UFRN"
  header_title = "Arthur Costa"
  header_subtitle = "Information Technology student at IMD/UFRN"
  home_image = "/images/avatar.jpeg"
  recent_posts = 5
  mainSections = ["posts", "post", "blog"]
  [params.style]
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "http://github.com/arthurcostaa"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/arthur-costa-4369a9224/"
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = "https://x.com/arthurcosta084"
  [[params.social]]
    fa_icon = "fa-solid fa-envelope fa-1x"
    href = "mailto:arthurcosta0ac@gmail.com"
